# Generated by Django 2.2.7 on 2020-02-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='NAMA PROJECT')),
                ('spk', models.CharField(max_length=30, verbose_name='NO SPK')),
                ('sumber', models.IntegerField(choices=[('1', 'APBN'), ('2', 'APBD TK. 1'), ('3', 'APBD TK. 2'), ('4', 'SWASTA'), ('5', 'DANA INTERNASIONAL')])),
                ('alamat', models.CharField(max_length=200)),
                ('kota', models.CharField(max_length=100, verbose_name='KOTA/KABUPATEN')),
                ('provinsi', models.CharField(max_length=30)),
                ('nilai', models.FloatField(verbose_name='NILAI PROJECT')),
                ('tgl_buat', models.TimeField(auto_now_add=True)),
                ('tgl_mulai', models.TimeField()),
                ('tgl_selesai', models.TimeField()),
            ],
        ),
    ]
