# Generated by Django 2.2.7 on 2020-02-07 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarproject',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daftarproject',
            name='tgl_buat',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daftarproject',
            name='tgl_mulai',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='daftarproject',
            name='tgl_selesai',
            field=models.DateField(),
        ),
    ]
